name: 🐛 Bug Report
description: Report a bug or issue with Truxe
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
        **Before submitting**, please:
        - Search existing issues to avoid duplicates
        - Check our [troubleshooting guide](https://docs.truxe.io/troubleshooting)
        - Ensure you're using the latest version

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have checked the troubleshooting guide
          required: true
        - label: I am using the latest version
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - API
        - CLI
        - Database
        - Documentation
        - SDK/Integration
        - Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Some functionality affected)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0, Windows 11]
        - Node.js version: [e.g. 20.10.0]
        - Truxe version: [e.g. 1.0.0]
        - Database: [e.g. PostgreSQL 16]
        - Deployment method: [e.g. Docker, Kubernetes, Dokploy]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant logs, error messages, or stack traces
      placeholder: Paste logs here...
      render: text

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive data)
      placeholder: |
        ```yaml
        # Your configuration here (remove secrets)
        ```
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or relevant information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this issue
