name: ❓ Question
description: Ask a question about Truxe
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about Truxe? We're here to help!
        
        **Before asking**, please:
        - Check our [documentation](https://docs.truxe.io)
        - Search existing issues and discussions
        - Try our [Discord community](https://discord.gg/truxe) for faster responses

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Getting Started
        - Authentication Flow
        - Configuration
        - Deployment
        - Integration
        - Security
        - Performance
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your use case
      placeholder: |
        What are you trying to achieve?
        What have you tried so far?
        What's your current setup?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Node.js version: [e.g. 20.10.0]
        - Truxe version: [e.g. 1.0.0]
        - Deployment method: [e.g. Docker, Kubernetes]

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: Screenshots, code snippets, error messages, etc.
